### ISSUE TITLE
NES ROMs have headers stripped unexpectedly

### ISSUE THREAD

**Issue by ahknight** [emmercm/igir#1369] opened 2024-10-06 15:58 UTC
### Paste the command

```
npx --yes igir@latest move zip test clean report \
  --dat "./DATs/No-Intro*PC*.zip" \
  --dat-name-regex-exclude "/encrypted/i" \
  --input "./${CONSOLE_GAMES}/" \
  --input "${CONSOLE_GAMES_BACKUPS}" \
  "${INPUTS[@]:-}" \
  --input-checksum-max CRC32 \
  --input-checksum-archives never \
  --output "./${CONSOLE_GAMES}" \
  --dir-dat-name \
  --overwrite-invalid \
  --clean-backup "${CONSOLE_GAMES_BACKUPS}" \
  --zip-exclude "*.{chd,iso,pbp,cue,bin}" \
  -v

```

### Describe the bug

When using the zipped daily from No-Intro, IGIR chooses to use the "unheadered" DAT for NES and strips the headers of all ROMs.

### Expected behavior

It should not strip headers from NES ROMs without confirmation.  There exists no flag to disable this "feature" and I can't get the ROMs to match the "Headered" DAT.

### Debug logs

This isn't a single case; this happens with any NES romset input and the full No-Intro DAT set.

### igir version

3.0.1

### Node.js version

22.9.0

### Operating system

macOS

**Comment by emmercm** [comment] 2024-10-07 14:47
Duplicate of https://github.com/emmercm/igir/issues/1346.

Igir isn't "choosing" the headerless DAT, your zip file provides it. The files that Igir writes will exactly match what DATs contain.

To ignore the DAT, use the `--dat-name-regex-exclude "/headerless/i" \` option. Example here: https://igir.io/usage/personal/#analogue-pocket

**Closed by emmercm** 2024-10-07 14:47 UTC
Labels: potential-bug

**Comment by ahknight** [comment] 2024-10-07 17:29
One doesn't expect a ROM organization tool to modify the ROMs, in general. I really think it needs an explicit switch to prevent changes to ROMs, especially given the focus on archival and preservation in this arena.

**Comment by emmercm** [comment] 2024-10-07 17:58
The behavior is documented [here](https://igir.io/roms/headers/#automatic-header-removal). When using the No-Intro daily download packs, both the headered and headerless DATs are provided. When following Igir's [best practices](https://igir.io/usage/best-practices/#file-outputs) with organizing written files by DAT (or only supplying one DAT at a time), both copies would be written, so there's no data loss. Igir will also prevent both DATs from writing to the same output location, to avoid any race conditions.

To me, this is expected behavior -- a headerless DAT cataloged headerless ROMs, and Igir knows how to fulfill that request. But I'll continue to listen to feedback.
