### ISSUE TITLE
More mame merged set edge cases

### ISSUE THREAD

**Issue by nottanumber** [emmercm/igir#724] opened 2023-09-30 02:36 UTC
### Paste the command

```ps
.\mame -verifyroms > verify_output_before.txt # no issues before
```

```ps
npx igir@latest zip copy test clean report --dat $MAME_EXE --input '.\MAME\**\*' --output .\ROMs-Sorted\ --merge-roms merged
```

followed by

```ps
.\mame -verifyroms > verify_output_after.txt # issues
```

### Describe the bug

these all seem like they could be the same underlying issue with one-off files missing. Leads me to think there are some duplicate files or conflicts shared among similar rom / bios / machines

```sh
neo-epo.bin NOT FOUND (tried in aes)
neocd.bin NOT FOUND (tried in neocdz)

hdboot.u32 NOT FOUND (tried in sfrush)

blitz1__.u32 NOT FOUND (tried in blitz)

rh-ix0897cezz.ic12 NOT FOUND (tried in x68000)
rh-ix0898cezz.ic11 NOT FOUND (tried in x68000)

cpc-200bw_v1_0 NOT FOUND (tried in perfect1)

341-0004-00.f8 NOT FOUND (tried in apple2)
laser 128 v4.3 871222.bin NOT FOUND (tried in laser128 apple2c)
342-0341-c.u6d NOT FOUND (tried in macplus)
342-0342-b.u8d NOT FOUND (tried in macplus)
```

### Expected behavior

`-verifyroms` would not change after running igir arcade merge strategy

### Debug logs

```sh
neo-epo.bin NOT FOUND (tried in aes)
```

### igir version

2.0.3

### Node.js version

20.6.1

### Operating system

win

**Comment by emmercm** [comment] 2023-09-30 04:09
I'm pretty sure this is because I'm ignoring the `romOf` attribute, I think that indicates a BIOS that's found elsewhere.

I really wish pleasuredome published a non-full, non-merged DAT for me to compare with.

**Comment by emmercm** [comment] 2023-09-30 04:54
I need to source a clean MAME set, but in the meantime could I ask you to test #727, @nottanumber?

Instructions here: https://github.com/emmercm/igir/pull/727#issuecomment-1741677560

**Comment by nottanumber** [comment] 2023-09-30 16:22
> I need to source a clean MAME set, but in the meantime could I ask you to test #727, @nottanumber?
> 
> Instructions here: [#727 (comment)](https://github.com/emmercm/igir/pull/727#issuecomment-1741677560)

only issue I see left is `c1541.zip`

```ps
325302-01.uab4 NOT FOUND (tried in c1541 c64)
901229-06 aa.uab5 NOT FOUND (tried in c1541 c64)
Fatal error: Required files are missing, the machine cannot be run.
```

igir did warn early

```ps
WARN:  c64: missing dependent ROM set: c1541
```

maybe a separate issue

**Comment by nottanumber** [comment] 2023-09-30 17:15
looks like `coh3002t.zip` and `sys573.zip` don't get created after the igir run either. Similar to `c1541.zip` above

**Comment by emmercm** [comment] 2023-09-30 17:55
Interesting, `igir` must think they're missing ROMs. Could you post an `unzip -v <file>` of them, similar to:

```
$ unzip -v igir-merged/100lions.zip
Archive:  igir-merged/100lions.zip
 Length   Method    Size  Cmpr    Date    Time   CRC-32   Name
--------  ------  ------- ---- ---------- ----- --------  ----
 4194304  Defl:N  2671977  36% 09-30-2023 17:25 8e34e360  100lionsa/30223811.u73
 4194304  Defl:N  2695794  36% 09-30-2023 17:25 735285e1  100lionsa/30223811.u86
 4194304  Defl:N  2700709  36% 09-30-2023 17:25 da7d2ed7  10219211.u73
 4194304  Defl:N  2721015  35% 09-30-2023 17:25 a1c71dd2  10219211.u86
--------          -------  ---                            -------
16777216         10789495  36%                            4 files

**Comment by emmercm** [comment] 2023-09-30 19:35
@nottanumber I'm not ignoring ROMs that haven't been dumped yet:

```xml
<machine name="c1541" sourcefile="devices/bus/cbmiec/c1541.cpp" isdevice="yes" runnable="no">
    <description>Commodore 1541 Disk Drive</description>
    <!-- ... -->
    <rom name="901229-04.uab5" bios="r4" size="8192" status="nodump" region="ucd5" offset="2000"/>
    <!-- ... -->
</machine>
```

**Comment by emmercm** [comment] 2023-09-30 20:17
New fix to test if you have time @nottanumber, it includes the previous one:

https://github.com/emmercm/igir/pull/728

**Comment by nottanumber** [comment] 2023-09-30 22:50
> Interesting, `igir` must think they're missing ROMs. Could you post an `unzip -v <file>` of them, similar to:
> 
> ```
> $ unzip -v igir-merged/100lions.zip
> Archive:  igir-merged/100lions.zip
>  Length   Method    Size  Cmpr    Date    Time   CRC-32   Name
> --------  ------  ------- ---- ---------- ----- --------  ----
>  4194304  Defl:N  2671977  36% 09-30-2023 17:25 8e34e360  100lionsa/30223811.u73
>  4194304  Defl:N  2695794  36% 09-30-2023 17:25 735285e1  100lionsa/30223811.u86
>  4194304  Defl:N  2700709  36% 09-30-2023 17:25 da7d2ed7  10219211.u73
>  4194304  Defl:N  2721015  35% 09-30-2023 17:25 a1c71dd2  10219211.u86
> --------          -------  ---                            -------
> 16777216         10789495  36%                            4 files
> ```

```
$ unzip -v coh3002t.zip
Archive:  coh3002t.zip
 Length   Method    Size  Cmpr    Date    Time   CRC-32   Name
--------  ------  ------- ---- ---------- ----- --------  ----
 1048576  Defl:N   134929  87% 1996-12-24 23:32 6225ec11  f35-01_m27c800.bin
 1048576  Defl:N   134417  87% 1996-12-24 23:32 cd15cc30  f35-01_m27c800_v1.bin
 2097152  Defl:N    84160  96% 1996-12-24 23:32 c48c8236  flash.u30
  524288  Defl:N   135299  74% 1996-12-24 23:32 03967fa7  m534002c-60.ic353
       8  Stored        8   0% 1996-12-24 23:32 235510b1  tt10.ic652
       8  Stored        8   0% 1996-12-24 23:32 6bb167b3  tt16
--------          -------  ---                            -------
 4718608           488821  90%                            6 files
```

```
$ unzip -v sys573.zip
Archive:  sys573.zip
 Length   Method    Size  Cmpr    Date    Time   CRC-32   Name
--------  ------  ------- ---- ---------- ----- --------  ----
  524288  Defl:X    63249  88% 1996-12-24 23:32 39ebb0ca  700a01,gchgchmp.22g
  524288  Defl:X    63188  88% 1996-12-24 23:32 11812ef8  700a01.22g
  524288  Defl:X    98997  81% 1996-12-24 23:32 6cf852af  700b01.22g
      64  Defl:X        6  91% 1996-12-24 23:32 131e0359  h8a01.bin
      64  Defl:X       14  78% 1996-12-24 23:32 508b057d  h8b01.bin
--------          -------  ---                            -------
 1572992           225454  86%                            5 files
```

**Comment by nottanumber** [comment] 2023-09-30 22:53
for `c64` thing seems like c1541 is a red herring

```
901226-01.u3 NOT FOUND (tried in c64)
901227-03.u4 NOT FOUND (tried in c64)
901225-01.u5 NOT FOUND (tried in c64)
906114-01.u17 NOT FOUND (tried in c64)
325302-01.uab4 NOT FOUND (tried in c1541 c64)
901229-06 aa.uab5 NOT FOUND (tried in c1541 c64)
Fatal error: Required files are missing, the machine cannot be run.
```

```
> .\mame -listxml c64 | sls '901229-06 aa.uab5'

                <rom name="901229-06 aa.uab5" bios="r6" size="8192" crc="3a235039" sha1="c7f94f4f51d6de4cdc21ecbb7e57bb209f0530c0" region="ucd5" offset="2000"/>
                <rom name="901229-06 aa.uab5" size="8192" crc="3a235039" sha1="c7f94f4f51d6de4cdc21ecbb7e57bb209f0530c0" region="ucd5" offset="2000"/>
```

**Comment by emmercm** [comment] 2023-10-01 19:17
I'm fairly sure there are regressions, specifically games that have ROMs with `status="nodump"`.

**Closed** 2023-10-01 20:00 UTC
Labels: bug
