### ISSUE TITLE
Cache File Location

### ISSUE THREAD

**Issue by maxexcloo** [emmercm/igir#1078] opened 2024-04-08 00:32 UTC
### Is your feature request related to a problem?

I'd like to be able to set the location of the `igir.cache` file.

### Describe the solution you'd like

A new flag that allows setting the location.

### Additional context

NA

**Comment by emmercm** [comment] 2024-04-08 00:47
Duplicate of https://github.com/emmercm/igir/issues/1060.

**Closed by emmercm** 2024-04-08 00:47 UTC
Labels: duplicate, enhancement

**Comment by maxexcloo** [comment] 2024-04-08 01:08
Apologies, I should have searched!
